config/routes.rb
Rails.application.routes.draw do
  get '/' => 'public/homes#top', as: "root"
  devise_for :customers, path: 'customer'
  scope module: :public do
    get '/homes/about' => 'homes#about'
    resource :customers, only: [:edit, :update]
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/quit' => 'customers#quit_update'
    get '/customers/my_page' => 'customers#show'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:create, :destroy, :update]
    get '/cart_items' => 'cart_items#cart'

    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#order_complete'
    resources :orders, only: [:new, :create, :show, :index]
    resources :items, only: [:index, :show]
    resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  devise_for :admins
  namespace :admin do
    devise_for :admins, skip: :all
    devise_scope :admin do
      get '/sign_in' => 'sessions#new'
      post '/sign_in' => 'sessions#create'
      delete '/sign_out' => 'sessions#destroy'
    end
    get '' => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    # patch 'admin/order_details/:id' => 'admin_order_details#update'
    resources :items, except: [:destroy]
    resources :genres, only: [:create, :index, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/item.rb
class Item < ApplicationRecord

  validates :image, presence: {message: 'を選択してください'}
  validates :name, presence: true
  validates :description, presence: true

  belongs_to :genre

  validates :price, presence: true,
                    numericality: { only_integer: true,
                                    greater_than_or_equal_to: 0
                                  }

  validates :is_sale, inclusion: {in: [true, false]}

  has_many :cart_items, dependent: :destroy

  attachment :image

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  before_action :authenticate_admin!
  layout 'admin'

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render 'new'
    end
  end

  def show
     @item = Item.find(params[:id])
     @genre = Genre.find(@item.genre_id)
  end

  def index
     @items = Item.page(params[:page]).per(10)
  end

  def edit
     @item = Item.find(params[:id])
  end

  def update
     @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render "edit"
    end
  end


  private
  def item_params
    params.require(:item).permit(:image, :name, :genre_id, :description, :price, :is_sale )
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<%= form_with model:@item, url: admin_item_path(@item.id), method: :patch,local:true do |f| %>
  <% if @item.errors.any? %>
    <div class="alert alert-position">
      <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row edit-title-admin-box">

      <h3 class="edit-title-admin">　商品編集</h3>
      <div class="col-lg-5">
        <% if @item.image.present? %>
          <%= attachment_image_tag @item, :image, id: :img_prev, size: "450x300" %>
        <% else %>
          <%= image_tag @item, :image, :fill, 450, 300, format: 'jpeg', id: :img_prev %>
        <% end %>
        <%= f.attachment_field :image, id: :item_img %>
        
         <script type="text/javascript">
          $(function() {
            function readURL(input) {
                if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
            $('#img_prev').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
                }
            }
            $("#item_img").change(function(){
                readURL(this);
            });
          });
        </script>
        
      </div>
      <div class="col-lg-6">
        <table class="table table-hover table-inverse">
          <tr>
            <td><%= f.label :商品名 %></td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td><%= f.label :商品説明 %></td>
            <td><%= f.text_field :description %></td>
          </tr>
          <tr>
            <td><%= f.label :ジャンル %></td>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td><br>
          </tr>
          <tr>
            <td><%= f.label :税抜価格 %></td>
            <td><%= f.text_field :price %> 円</td><br>
          </tr>
          <tr>
            <td><%= f.label :販売ステータス %>
            <td><%= f.select :is_sale, [["販売中", "1"],["販売停止中", "0"]] %></td><br>
          </tr>
        </table>
      <div id = "item-action-btn">
        <%= f.submit :変更を保存, class: "btn btn-default btn-lg btn-info " %>
      </div>
      <% end %>
    </div>

    </div>
  </div>

app/views/admin/items/index.html.erb
<div class= "container">
  <div class="row index-title-box">
  	
  	<h3 class="index-title">　商品一覧</h3>
    <div class="col-sm-12">
			<table class='table table-hover table-inverse'>
				<thead>
					<tr class="active">
						<th>商品ID</th>
						<th>商品名</th>
						<th>税抜価格</th>
						<th>ジャンル</th>
						<th>ステータス</th>
					</tr>
				</thead>

				<tbody>
					<% @items.each do |item| %>
					<tr>
						<td><%= item.id %></td>
						<td><%= link_to item.name, admin_item_path(item.id) %></td>
						<td><%= item.price.to_s(:delimited) %>円</td>
						<td><%= Genre.find(item.genre_id).name%></td>
						<td>
			        <% if item.is_sale == true %>
			          販売中
			        <% else %>
			          販売停止
			        <% end %>
			      </td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<div class="pagenation center-block"><%= paginate @items %></div>
			<div id = "item-action-btn">
			  <%= link_to " 新規商品登録へ ", new_admin_item_path, class: "btn btn-default btn-lg btn-info " %>
			</div>
    </div>
    
  </div>
</div>

app/views/admin/items/new.html.erb
<%= form_with model:@item, url: admin_items_path, method: :post, local:true do |f| %>



  <div class="container">
    <div class="row new-item-box">

      <h3 class="new-title">　商品新規登録</h3>
      <div class="col-lg-5 image-position">
        <% if @item.image.present? %>
          <%= image_tag :image, id: :img_prev, size: "450x300" %>
        <% else %>
          <%= image_tag "no_image_yoko.jpg", id: :img_prev, size: "450x300" %>
        <% end %>
        <%= f.attachment_field :image, id: :item_img, size: "450x300" %>
        <script type="text/javascript">
          $(function() {
            function readURL(input) {
                if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
            $('#img_prev').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
                }
            }
            $("#item_img").change(function(){
                readURL(this);
            });
          });
        </script>

      </div>

      <div class="col-lg-6">
        <% if @item.errors.any? %>
          <div class="alert alert-position">
            <ul>
              <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <table class="table table-hover table-inverse">
          <tr>
            <td><%= f.label :商品名 %></td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td><%= f.label :商品説明 %></td>
            <td><%= f.text_area :description %></td>
          </tr>
          <tr>
            <td><%= f.label :ジャンル %></td>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択してください"  %></td><br>
          </tr>
          <tr>
            <td><%= f.label :税抜価格 %></td>
            <td><%= f.text_field :price %> 円</td><br>
          </tr>
          <tr>
            <td><%= f.label :販売ステータス %>
            <td><%= f.select :is_sale, [["販売中", "1"],["販売停止中", "0"]] %></td><br>
          </tr>
        </table>
        <div id = "item-action-btn">
          <%= f.submit :新規登録, class: "btn btn-default btn-lg btn-info " %>
        </div>
        <% end %>
      </div>

    </div>
  </div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row show-item-box">
    
    <h3 class="show-title">　商品詳細</h3>
    <div class="col-sm-5 item-image-show">
      <%= attachment_image_tag @item, :image, :fill, 450, 300, format: 'jpeg' %>
    </div>
    
    <div class="col-sm-6 item-subscribe">
      <table class="table table-hover table-inverse">
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
          
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.description %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @genre.name %></td>
        </tr>
        <tr>
          <td>税込価格（税抜価格）</td>
          <td><%= ((@item.price * 1.1).round(2)).ceil.to_s(:delimited)  %>（<%= @item.price.to_s(:delimited) %>）円</td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <% if @item.is_sale == true %>
              販売中
            <% else %>
              販売停止
            <% end %>
          </td>
        </tr>
      </table>
      <div id = "item-action-btn">
        <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-default btn-lg btn-info " %>
    </div>
    </div>

    
  </div>
</div>