config/routes.rb
Rails.application.routes.draw do
  get '/' => 'public/homes#top', as: "root"
  devise_for :customers, path: 'customer'
  scope module: :public do
    get '/homes/about' => 'homes#about'
    resource :customers, only: [:edit, :update]
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/quit' => 'customers#quit_update'
    get '/customers/my_page' => 'customers#show'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:create, :destroy, :update]
    get '/cart_items' => 'cart_items#cart'

    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#order_complete'
    resources :orders, only: [:new, :create, :show, :index]
    resources :items, only: [:index, :show]
    resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  devise_for :admins
  namespace :admin do
    devise_for :admins, skip: :all
    devise_scope :admin do
      get '/sign_in' => 'sessions#new'
      post '/sign_in' => 'sessions#create'
      delete '/sign_out' => 'sessions#destroy'
    end
    get '' => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    # patch 'admin/order_details/:id' => 'admin_order_details#update'
    resources :items, except: [:destroy]
    resources :genres, only: [:create, :index, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true,
                             format: {
                               with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                               message: "を全角カタカナのみで入力して下さい。"
                             }
  validates :first_name_kana, presence: true,
                               format: {
                               with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                               message: "を全角カタカナのみで入力して下さい。"
                             }

  validates :email, presence: true

  validates :postcode, presence: true,
                       format: {
                         with: /\A\d{7}\z/,
                         message: "を7桁の数値で入力して下さい。"
                       }
  validates :address, presence: true
  validates :phone_number, presence: true,
                           format: {
                             with:   /\A\d{10,11}\z/,
                             message: "を10桁もしくは11桁の数値で入力して下さい。"
                           }
  validates :encrypted_password, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :shipping_addresses

  def active_for_authentication?
    super && (self.is_quit == false)
  end

  def now_address
     self.postcode + self.address + self.last_name + self.first_name
  end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!
  layout 'admin'

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(params[:id])
    else
      render 'edit'
    end
  end

  private
  def customer_params
     params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postcode, :address, :phone_number, :is_quit)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">

    <% if @customer.errors.any? %>
      <div class="alert alert-position">
        <ul>
          <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-md-10 col-md-offset-3">
      <div class="customer-title-area">
        <h3 class="customer-edit-title">　<%= @customer.last_name %> <%= @customer.first_name %>さんの会員情報編集　</h3>
      </div>
      <%= form_with url: admin_customer_path(@customer.id), model:@customer,　id: 'new_user', class: 'new_user', local: true do |f| %>
        <form class="form-horizontal">
          <div class="form-group">
            <label for="inputName3" class="col-sm-2 control-label"><%= f.label :会員ID %></label>
              <div class="col-sm-3">
                <%= @customer.id %>
              </div>
          </div>
          <br></br><br></br>
          <div class="form-group">
            <label for="inputName3" class="col-sm-2 control-label"><%= f.label :氏名 %></label>
              <div class="col-sm-3">
                <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control", id:"inputName3" %>
              </div>
              <div class="col-sm-3">
                <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "form-control", id:"inputName3" %>
              </div>
          </div>
          <br></br><br></br>
          <div class="form-group">
            <label for="inputName3" class="col-sm-2 control-label"><%= f.label :フリガナ %></label>
              <div class="col-sm-3">
                <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", class: "form-control", id:"inputName3" %>
              </div>
              <div class="col-sm-3">
                <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", class: "form-control", id:"inputName3" %>
              </div>
          </div>
          <br></br><br></br>
          <div class="form-group">
          <label for="inputPostcode3" class="col-sm-2 control-label"><%= f.label :"郵便番号(ハイフンなし)" %></label>
            <div class="col-sm-5">
              <%= f.text_field :postcode, autofocus: true, autocomplete: "postcode", class: "form-control", id:"inputPostcode3" %>
            </div>
          </div>
          <br></br><br></br>
          <div class="form-group">
            <label for="inputAddress3" class="col-sm-2 control-label"><%= f.label :住所 %></label>
              <div class="col-sm-5">
                <%= f.text_field :address, autofocus: true, autocomplete: "address", class: "form-control", id:"inputAddress3" %>
              </div>
          </div>
          <br></br><br></br>
          <div class="form-group">
            <label for="inputPhonenumber3" class="col-sm-2 control-label"><%= f.label :電話番号 %></label>
              <div class="col-sm-5">
                <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number", class: "form-control", id:"inputPhonenumber3" %>
              </div>
          </div>
          <br></br><br></br>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label"><%= f.label :メールアドレス %></label>
              <div class="col-sm-5">
                <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", id:"inputEmail3" %>
              </div>
          </div>
          <br></br><br></br>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label"><%= f.label :会員ステータス %></label>
              <div class="col-sm-5">
                <%= f.radio_button :is_quit, "false" %>
                <%= f.label :有効, class: "is_quit_label" %>
                <%= f.radio_button :is_quit, "true" %>
                <%= f.label :退会済み, class: "is_quit_label" %>
              </div>
          </div>
          <br></br><br></br>
          <div class="form-group">
            <div class="col-md-offset-2 col-md-7 customer-edit-button-position">
              <%= f.submit "　変更を保存する　", class:"btn btn-primary btn-lg" %>
            </div>
          </div>
        </form>
      <% end %>
    </div>

  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row custmer-index-box">
  	
  	<h3 class="customer-index-title">　会員一覧</h3>
  	
  	<div class="col-md-8 col-md-offset-2">
			<table class="table table-hover table-inverse">
				<thead>
					<tr class="active">
						<th>会員ID</th>
						<th>氏名</th>
						<th>メールアドレス</th>
						<th>ステータス</th>
					</tr>
				</thead>
				
				<tbody>
					<% @customers.each do |customer| %>
					<tr>
						<td><%= customer.id %></td>
						<td>
							<%= link_to admin_customer_path(customer.id) do %>
								<%= customer.last_name %>
								<%= customer.first_name %> 様
							<% end %>
						</td>
						<td><%= customer.email %></td>
						<td>
			        <% if customer.is_quit == true %>
			          退会済
			        <% else %>
			          有効
			        <% end %>
			      </td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<div class="pagenation"><%= paginate @customers %></div>
				
		</div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<h3 class="show-title-admin">　<%= @customer.last_name %> <%= @customer.first_name  %>さんの会員詳細　</h3>
<div class="container">
  <div class="row">

    <div class="col-lg-8">

      <table class="customer-table ">
        <tr>
          <td>顧客ID</td>
          <td><%= @customer.id %></td>
          <td>
            <% if @customer.is_quit == true %>
              <span class="label label-danger">退会済</span>
            <% else %>
              <span class="label label-info">有効会員</span>
            <% end %>
          </td>

        </div>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.last_name %></td>
          <td><%= @customer.first_name  %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= @customer.last_name_kana %></td>
          <td><%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postcode %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>

        <tr>
          <td>電話番号</td>
          <td><%= @customer.phone_number %></td>
        </tr>
      </table>
      <div class="col-md-2">
        <div id = "customer-action-btn">
          <%= link_to "　編集する　", edit_admin_customer_path(@customer), class: "btn btn-default btn-primary " %>
        </div>
      </div>
      <div class="col-md-2">
        <div id = "orders-action-btn">
          <%= link_to "　注文履歴一覧を見る　", admin_orders_path(order_sort: 1,customer_id: @customer), class: "btn btn-default btn-primary " %>
        </div>
      </div>
  </div>
</div>