config/routes.rb
Rails.application.routes.draw do
  get '/' => 'public/homes#top', as: "root"
  devise_for :customers, path: 'customer'
  scope module: :public do
    get '/homes/about' => 'homes#about'
    resource :customers, only: [:edit, :update]
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/quit' => 'customers#quit_update'
    get '/customers/my_page' => 'customers#show'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:create, :destroy, :update]
    get '/cart_items' => 'cart_items#cart'

    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#order_complete'
    resources :orders, only: [:new, :create, :show, :index]
    resources :items, only: [:index, :show]
    resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  devise_for :admins
  namespace :admin do
    devise_for :admins, skip: :all
    devise_scope :admin do
      get '/sign_in' => 'sessions#new'
      post '/sign_in' => 'sessions#create'
      delete '/sign_out' => 'sessions#destroy'
    end
    get '' => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    # patch 'admin/order_details/:id' => 'admin_order_details#update'
    resources :items, except: [:destroy]
    resources :genres, only: [:create, :index, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items

  enum payment_method: {クレジットカード: 0, 銀行振込: 1 }
  enum status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    
    before_action :authenticate_admin!
    layout 'admin'

    def index #注文履歴一覧
        case params[:order_sort]
        when "0"
           @orders = Order.where(created_at: Date.today.in_time_zone.all_day).page(params[:page]).per(10)
        when "1"
           @customer = Customer.find(params[:customer_id])
           @orders = @customer.orders.page(params[:page]).per(10)
        else
           @orders = Order.all.page(params[:page]).per(10)
        end
    end

    def show #注文履歴詳細
        @order = Order.find(params[:id])
        @order_items = OrderItem.where(order_id: params[:id])
        @total_fee = (@order.billing_amount - @order.shipping_fee).to_s(:delimited)
    end

    def update #注文ステータス
        @order = Order.find(params[:id])
        @order.update(order_params)
         if @order.status == "入金確認"
            @order.order_items.update(production_status: "製作待ち")
         end
         redirect_to admin_order_path(params[:id])
    end

    def new
      @order = Order.new
    end

    private

    def order_params
        params.require(:order).permit(:status)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<h3 class="order-admin-title-box"><span class="order-admin-title">　注文履歴一覧　</span></h3>
<div class="container">
  <div class="row-sm-12 order-info-table">
    
    <div class="col-sm-12 table-responsive">
    <!--注文履歴一覧テーブル-->
      <table class="table table-hover">
        <thead>
          <tr class="success">
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to order.created_at.strftime("%Y/%m/%d　%H:%M"), admin_order_path(order.id)  %></td>
              <td><%= order.customer.last_name %> <%= order.customer.first_name %> 様</td>
              <% count = 0 %>
              <% order.order_items.each do |order_item| %>
                <%count += order_item.item_count %>
              <% end %>
              <td><%= count %>個</td>
              <td><%= order.status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <!--ページネーション-->
    <div class="pagenation"><%= paginate @orders %></div>
    </div>
    
  </div>
</div>

app/views/admin/orders/show.html.erb
<h3 class="order-info-show-title"><span class="order-info-title">　注文履歴詳細　</span></h3>
<div class="container-fluid">

  <div class="row-sm-12 order-info-show-table">
  <!--注文者情報テーブル-->
  <%= form_with model:@order, url: admin_order_path, method: :patch,local:true do |f| %>
    <table class="table">
        <tr>
          <th class="">購入者</th>
          <td><%= link_to admin_customer_path(@order.customer.id) do %>
      					<%= @order.customer.last_name %>
      					<%= @order.customer.first_name %>
              <% end %> 様</td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.postcode %> <%= @order.address %><br>
              <%= @order.name %> 様
              </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
            <td>
              <%= f.select :status, Order.statuses.keys %>
              <%= f.submit :更新, class: "btn btn-md btn-primary" %>
            </td>
          <% end %>

        </tr>
      </table>
  </div>

  <div class="row-sm-12 order-info-show-price-table">
    <div class="col-sm-9 productionstatus">
      <table class= "table table-noborder table-hover table-inverse">
        <thead>
          <tr class="active">
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @order_items.each do |order_item| %>
            <tr>
              <td><%= order_item.item.name %></td>
              <td><%= order_item.price_including_tax %>円</td>
              <td><%= order_item.item_count %>個</td>
              <td><%= (order_item.price_including_tax * order_item.item_count).to_s(:delimited) %>円</td>

              <!--制作ステータス-->
              <%= form_with model: order_item, url: admin_order_detail_path(order_item.id), method: :patch,local:true do |f| %>

                <td><%= f.select :production_status, ["着手不可","製作待ち","製作中","製作完了"] %></td>
                <td><%= f.submit :更新, class: "btn btn-md btn-primary" %></td>
              <% end %>
            <% end %>
            </tr>
        </tbody>
      </table>
    </div>

    <div class="col-sm-3 order-info-show">
    <!--金額情報テーブル-->
      <table class="table table-noborder">
        <tr>
          <th class="success">商品合計</th>
          <td><%= @total_fee %>円</td>
        </tr>
        <tr>
          <th class="success">送料</th>
          <td><%= @order.shipping_fee %>円</td>
        </tr>
        <tr>
          <th class="success">請求金額合計</th>
          <td><%= @order.billing_amount.to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>

  </div>

</div>