config/routes.rb
Rails.application.routes.draw do
  get '/' => 'public/homes#top', as: "root"
  devise_for :customers, path: 'customer'
  scope module: :public do
    get '/homes/about' => 'homes#about'
    resource :customers, only: [:edit, :update]
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/quit' => 'customers#quit_update'
    get '/customers/my_page' => 'customers#show'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:create, :destroy, :update]
    get '/cart_items' => 'cart_items#cart'

    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#order_complete'
    resources :orders, only: [:new, :create, :show, :index]
    resources :items, only: [:index, :show]
    resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  end

  devise_for :admins
  namespace :admin do
    devise_for :admins, skip: :all
    devise_scope :admin do
      get '/sign_in' => 'sessions#new'
      post '/sign_in' => 'sessions#create'
      delete '/sign_out' => 'sessions#destroy'
    end
    get '' => 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    # patch 'admin/order_details/:id' => 'admin_order_details#update'
    resources :items, except: [:destroy]
    resources :genres, only: [:create, :index, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :item_count, presence: {message: 'を選択してください'}, numericality: { only_integer: true, greater_than: 0}

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true,
                             format: {
                               with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                               message: "を全角カタカナのみで入力して下さい。"
                             }
  validates :first_name_kana, presence: true,
                               format: {
                               with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                               message: "を全角カタカナのみで入力して下さい。"
                             }

  validates :email, presence: true

  validates :postcode, presence: true,
                       format: {
                         with: /\A\d{7}\z/,
                         message: "を7桁の数値で入力して下さい。"
                       }
  validates :address, presence: true
  validates :phone_number, presence: true,
                           format: {
                             with:   /\A\d{10,11}\z/,
                             message: "を10桁もしくは11桁の数値で入力して下さい。"
                           }
  validates :encrypted_password, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :shipping_addresses

  def active_for_authentication?
    super && (self.is_quit == false)
  end

  def now_address
     self.postcode + self.address + self.last_name + self.first_name
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true, uniqueness: true

end

app/models/item.rb
class Item < ApplicationRecord

  validates :image, presence: {message: 'を選択してください'}
  validates :name, presence: true
  validates :description, presence: true

  belongs_to :genre

  validates :price, presence: true,
                    numericality: { only_integer: true,
                                    greater_than_or_equal_to: 0
                                  }

  validates :is_sale, inclusion: {in: [true, false]}

  has_many :cart_items, dependent: :destroy

  attachment :image

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items

  enum payment_method: {クレジットカード: 0, 銀行振込: 1 }
  enum status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum production_status: {着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  validates :postcode, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def full_address
    self.postcode + self.address + self.name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  before_action :authenticate_admin!
  layout 'admin'

  def top
    range = Date.today.beginning_of_day..Date.today.end_of_day
    @orders = Order.where(created_at: range)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  before_action :authenticate_admin!
  layout 'admin'

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render 'new'
    end
  end

  def show
     @item = Item.find(params[:id])
     @genre = Genre.find(@item.genre_id)
  end

  def index
     @items = Item.page(params[:page]).per(10)
  end

  def edit
     @item = Item.find(params[:id])
  end

  def update
     @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render "edit"
    end
  end


  private
  def item_params
    params.require(:item).permit(:image, :name, :genre_id, :description, :price, :is_sale )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when  Customer
      root_path
    when Admin
      admin_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when  :customer
      root_path
    when :admin
      admin_sign_in_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_datails_helper.rb
module Admin::OrderDatailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_admin_header.html.erb
<header class="navbar navbar-default">
  <div class="container-fluid">

      <!--ロゴ-->
      <nav class="nav navbar-header navbar-left">
        <div class="logo">
          <%= link_to root_path do %>
            <%= image_tag 'logo.jpg', class: "logo_image", fallback: "ロゴ画像" %>
          <% end %>
          <span class="header-text">　長野県にある小さな洋菓子店</span>
        </div>
      </nav>

      <!--メニューボタン-->
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if admin_signed_in? %>
            <li class="button-admin"><%= link_to "商品一覧", admin_items_path, class:"btn btn-default btn-lg admin-button" %> </li>
            <li class="button-admin"><%= link_to "会員一覧", admin_customers_path, class:"btn btn-default btn-lg admin-button" %></li>
            <li class="button-admin"><%= link_to "注文履歴一覧", admin_orders_path, class:"btn btn-default btn-lg admin-button" %></li>
            <li class="button-admin"><%= link_to "ジャンル一覧", admin_genres_path, class:"btn btn-default btn-lg admin-button" %></li>
            <li class="button-admin"><%= link_to "ログアウト", admin_sign_out_path, method: :delete, class:"btn btn-default btn-lg admin-button" %></li>
          <% else %>
            <li class="button-admin"><%= link_to " About ", homes_about_path, class:"btn btn-default btn-lg" %></li>
            <li class="button-admin"><%= link_to " 商品一覧 ", items_path, class:"btn btn-default btn-lg" %></li>
            <li class="button-admin"><%= link_to " 新規登録 ", new_customer_registration_path, class:"btn btn-default btn-lg" %></li>
            <li class="button-admin"><%= link_to " ログイン ", new_customer_session_path, class:"btn btn-default btn-lg" %></li>
          <% end %>
        </ul>
      </nav>
      <br></br><br></br></br>
    <% if admin_signed_in? %>
    <div class="search-form">
      <%= form_tag(items_path,:method => 'get') do %>
        <%= text_field_tag :name %>
        <%= submit_tag '検索' %>
      <% end %>
    </div>
    <% end %>
  </div>
</header>

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <p class="footer-text">©2020 asagao-cake</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="container-fluid">

      <!--ロゴ-->
      <nav class="nav navbar-header navbar-left">
        <div class="logo">
          <%= link_to root_path do %>
            <%= image_tag 'logo.jpg', class: "logo_image", fallback: "ロゴ画像" %>
          <% end %>
          <span class="header-text">　長野県にある小さな洋菓子店</span>
        </div>
      </nav>

      <!--メニューボタン-->
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if customer_signed_in? %>
            <li class="button greeting">ようこそ　<%= current_customer.last_name %> <%= current_customer.first_name %>さん！　</li>
            <li class="button"><%= link_to " マイページ ", customers_my_page_path, class:"btn btn-default btn-lg" %></li>
            <li class="button"><%= link_to " 商品一覧 ", items_path, class:"btn btn-default btn-lg" %></li>
            <li class="button"><%= link_to " カート ", cart_items_path, class:"btn btn-default btn-lg" %></li>
            <li class="button"><%= link_to " ログアウト ", destroy_customer_session_path, method: :delete, class:"btn btn-default btn-lg" %></li>
          <% else %>
            <li class="button"><%= link_to " About ", homes_about_path, class:"btn btn-default btn-lg" %></li>
            <li class="button"><%= link_to " 商品一覧 ", items_path, class:"btn btn-default btn-lg" %></li>
            <li class="button"><%= link_to " 新規登録 ", new_customer_registration_path, class:"btn btn-default btn-lg" %></li>
            <li class="button"><%= link_to " ログイン ", new_customer_session_path, class:"btn btn-default btn-lg" %></li>
          <% end %>
        </ul>
      </nav>
      <br></br><br></br>
  </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsagaoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/admin_header' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsagaoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="fix-wrapper">
      <%= render 'layouts/header' %>
      <main><%= yield %></main>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>